id: A2692B477
title: 'The Merry Sea of Blessings: A Guru Yoga of the Lord of Sages, Peerless Teacher
  of All, Including the Devas'
type: translation
pechas:
- I3513842B
- I8FFF48F1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:13:31.226372
  last_modified_at: 2023-01-04 12:13:31.226379
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I3513842B/E4EF: 5FFD
  I8FFF48F1/3EF9: 5FFD
